2023-01-25 08:05:12,455 - ERROR - service.py:98 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'rds.meunagumo.com.br' (timed out)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
